environment: production
env: prod

image:
  tag: "prod"

service:
  type: ClusterIP
  port: 80

container:
  envFrom:
  - secretRef: 
      name: lovevery-secrets
    
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

autoscaling:
  enabled: false
